routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('task', 'TaskController');

Route::get('/', function(){
	return redirect()->route('task.index');
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $table = 'tasks';
    protected $fillable = ['name', 'description', 'status'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Models\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::orderBy('created_at', 'desc')->paginate(5);


        return view('tasks.index')->with('tasks', $tasks);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        // $activity = 'todo';
        // if($activity == 'notes'){
        //     return view('tasks.notes');
        // }
        // else{
        //     return view('tasks.create');
        // }

        // $task = new Task;

        // $task->name = $request->input('name');
        // $task->description = $request->input('description');
        // $task->status = $request->input('status');

        // $task->save();

        // return response()->json($task);


        return view('tasks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255|min:2',
            'description' => 'required|string|max:10000|min:10',
        ]);

        $task = new Task;

        $task->name = $request->name;
        $task->description = $request->description;
        $task->status = $request->status;

        $task->save();

        Session::flash('success', 'Created Task Successfully');

        return redirect()->route('task.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);
        return view('tasks.edit')->with('task', $task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255|min:2',
            'description' => 'required|string|max:10000|min:10',
        ]);

        $task = Task::find($id);

        $task->name = $request->name;
        $task->description = $request->description;
        $task->status = $request->status;

        $task->save();

        Session::flash('success', 'Updated Task Successfully');

        return redirect()->route('task.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);

        $task->delete();

        Session::flash('success', 'Deleted Task Successfully');

        return redirect()->route('task.index');
    }

    public function note()
    {
        return view('tasks.notes');
    }
}

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>To Do List App - @yield('title')</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<style type="text/css">
		.pagination{
			justify-content: center;
		}
	</style>
</head>
<body>
	<div class="container mt-3">
		@include('partials.messages')
		@yield('content')
	</div>
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

resources/views/partials/messages.blade.php
{{-- Primary Alert --}}
@if(Session::has('primary'))
	<div class="alert alert-primary alert-dismissible fade show" role="alert">
		<strong>Note to User:</strong> {{ Session::get('primary') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Secondary Alert --}}
@if(Session::has('secondary'))
	<div class="alert alert-secondary alert-dismissible fade show" role="alert">
		<strong>Note to User:</strong> {{ Session::get('secondary') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Success Alert --}}
@if(Session::has('success'))
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		<strong>Success:</strong> {{ Session::get('success') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Danger Alert --}}
@if(Session::has('danger'))
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<strong>Error:</strong> {{ Session::get('danger') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Warning Alert --}}
@if(Session::has('warning'))
	<div class="alert alert-warning alert-dismissible fade show" role="alert">
		<strong>Something Went Wrong!</strong>
		<br>
		{{ Session::get('warning') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Informational Alert --}}
@if(Session::has('info'))
	<div class="alert alert-info alert-dismissible fade show" role="alert">
		<strong>Heads Up!</strong> {{ Session::get('info') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Light Alert --}}
@if(Session::has('light'))
	<div class="alert alert-light alert-dismissible fade show" role="alert">
		<strong>Note to User:</strong> {{ Session::get('light') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Dark Alert --}}
@if(Session::has('dark'))
	<div class="alert alert-dark alert-dismissible fade show" role="alert">
		<strong>Note to User:</strong> {{ Session::get('dark') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Authentication Alerts --}}
@if (session('status'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
	<strong>Note to User:</strong> {{ session('status') }}

	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
@endif

{{-- If the page has any errors passed to it --}}
@if(count($errors) > 0)

	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<strong>Errors:</strong>

		<ul>
			@foreach($errors->all() as $error)
				
				<li>{{ $error }}</li>

			@endforeach
		</ul>

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>

@endif

resources/views/tasks/create.blade.php
@extends('layouts.main')

@section('title', 'Create Task')

@section('content')
	<div class="row">
		<div class="col-sm-12">
			<h1>Create Task</h1>
			{!!	Form::open(['route' => 'task.store', 'method' => 'POST']) !!}
				@component('components.taskForm')
				@endcomponent
			{!! Form::close() !!}
		</div>
	</div>
	

@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit Task')

@section('content')
	<div class="row">
		<div class="col-sm-12">
			<h1>Edit Task</h1>
			{!!	Form::model($task, ['route' => ['task.update', $task->id], 'method' => 'PUT']) !!}
				@component('components.taskForm')
				@endcomponent
			{!! Form::close() !!}
		</div>
	</div>
	

@endsection

resources/views/tasks/index.blade.php
@extends('layouts.main')

@section('title', 'My To Do List')

@section('content')

	<div class="row mb-3">
		<div class="col-sm-5">
			<!-- <a href="{{ route('task.create')}}" class="btn btn-success">Switch to Notes Lists</a> -->
		</div>
		<div class="col-sm-3">
			<h2 class="justify-content-center">My To Do List</h2>
		</div>
		<div class="col-sm-4 text-right">
			<a href="{{ route('task.create')}}" class="btn btn-success">Create New Task</a>
		</div>
	</div>

	@if($tasks->count() == 0)
		<h3>No current task/s listed.</h3>
	@else

	@foreach($tasks as $task)
		<div class="row wrap">
			<div class="col-sm-12 mt-3">
				<div class="card border-secondary mb-3">
				  <div class="card-header"><h3>{{ $task->name }}</h3></div>
				  <div class="card-body text-dark">
				    <p class="card-text">{{ $task->description }}</p>
				    {!! Form::open(['route' => ['task.destroy', $task->id], 'method' => 'DELETE'])!!}
					    <a href="{{ route('task.edit', $task->id)}}" class="btn btn-sm btn-primary">Edit Task</a>
					    <button type="submit" class="btn btn-sm btn-danger">Remove Task</button>
				    {!! Form::close() !!}
				  </div>
				<div class="card-footer">
			      <small class="text-muted">Status: {{ $task->status }}</small>
			    </div>
				</div>
			</div>
		</div>
	@endforeach
	@endif

	<div class="row justify-content-center">
		<div class="col-sm-6 text-center">
			{{ $tasks->links() }}
		</div>
	</div>
@endsection

resources/views/tasks/notes.blade.php
@extends('layouts.main')

@section('title', 'Create Note')

@section('content')
	<div class="row">
		<div class="col-sm-12">
			<h1>Create Note</h1>
			{!!	Form::open(['route' => 'task.store', 'method' => 'POST']) !!}
				@component('components.notesForm')
				@endcomponent
			{!! Form::close() !!}
		</div>
	</div>
	

@endsection

resources/views/tasks/notesIndex.blade.php
@extends('layouts.main')

@section('title', 'My Notes List')

@section('content')

	<div class="row mb-3">
		<div class="col-sm-5">
			<a href="{{ route('task.create')}}" class="btn btn-success">Switch to To Do Lists</a>
		</div>
		<div class="col-sm-3">
			<h2 class="justify-content-center">My Notes List</h2>
		</div>
		<div class="col-sm-4 text-right">
			<a href="{{ route('task.create')}}" class="btn btn-success">Create New Notes</a>
		</div>
	</div>
		
		<div class="row wrap">
			<div class="col-sm-12 mt-3">
				<div class="card text-white bg-info mb-3" style="max-width: 18rem;">
				  <div class="card-header">Header</div>
				  <div class="card-body">
				    <h5 class="card-title">Info card title</h5>
				    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
				  </div>
				</div>
			</div>
		</div>

	<div class="row justify-content-center">
		<div class="col-sm-6 text-center">
			{{ $tasks->links() }}
		</div>
	</div>
@endsection